-- Seed data for CELPIP Training App

-- Insert sample vocabulary items
INSERT INTO public.vocab_items (lemma, pos, cefr, topic, definition, examples) VALUES
('accommodate', 'verb', 'B2', 'housing', 'To provide lodging or space for someone', '["The hotel can accommodate up to 200 guests.", "We need to accommodate different learning styles."]'),
('proficiency', 'noun', 'C1', 'education', 'A high degree of skill or expertise', '["She demonstrated great proficiency in French.", "Language proficiency is required for this position."]'),
('sustainable', 'adjective', 'B2', 'environment', 'Able to continue over a period of time without harming the environment', '["We need sustainable energy solutions.", "The company adopted sustainable business practices."]'),
('collaborate', 'verb', 'B1', 'work', 'To work together with someone to produce something', '["Teams must collaborate effectively to succeed.", "We collaborated on the research project."]'),
('innovation', 'noun', 'B2', 'technology', 'A new method, idea, or product', '["The company is known for its innovation.", "Technological innovation drives progress."]'),
('resilient', 'adjective', 'C1', 'character', 'Able to recover quickly from difficulties', '["She is remarkably resilient in the face of challenges.", "The community showed resilient spirit after the disaster."]'),
('advocate', 'noun', 'B2', 'social', 'A person who publicly supports a particular cause', '["She is an advocate for children''s rights.", "Environmental advocates work to protect nature."]'),
('diverse', 'adjective', 'B1', 'society', 'Including people or things that are very different from each other', '["The city has a diverse population.", "We need diverse perspectives to solve this problem."]'),
('efficient', 'adjective', 'B1', 'work', 'Working well without wasting time or money', '["The new system is more efficient.", "We need efficient use of resources."]'),
('authentic', 'adjective', 'B2', 'culture', 'Genuine and real, not false or copied', '["The restaurant serves authentic Italian food.", "She has an authentic personality."]');

-- Insert sample passages for reading and listening
INSERT INTO public.passages (skill, level, topic, source, content_text, audio_url, meta) VALUES
('reading', 7, 'environment', 'Environmental Science Journal', 'Climate change represents one of the most significant challenges facing humanity in the 21st century. The scientific consensus is clear: human activities, particularly the burning of fossil fuels, are driving unprecedented changes in Earth''s climate system. These changes manifest in rising global temperatures, melting polar ice caps, and increasingly extreme weather events. However, the situation is not without hope. Renewable energy technologies, such as solar and wind power, have become increasingly cost-effective and widespread. Many countries are implementing policies to reduce greenhouse gas emissions and transition to cleaner energy sources. The key to addressing climate change lies in both individual actions and collective policy decisions that prioritize sustainability and environmental protection.', NULL, '{"word_count": 120, "reading_time": 2, "difficulty": "intermediate"}'),
('reading', 9, 'technology', 'Tech Innovation Magazine', 'Artificial Intelligence (AI) has transformed from a science fiction concept to a fundamental technology reshaping industries worldwide. Machine learning algorithms now power everything from recommendation systems to autonomous vehicles. The rapid advancement of AI has raised important questions about ethics, privacy, and the future of work. While some fear that AI will replace human workers, others argue that it will augment human capabilities and create new opportunities. The development of AI requires careful consideration of bias, transparency, and accountability. As we integrate AI more deeply into our daily lives, it becomes crucial to ensure that these systems serve human interests and promote social good rather than perpetuate existing inequalities.', NULL, '{"word_count": 130, "reading_time": 2.5, "difficulty": "advanced"}'),
('listening', 6, 'education', 'Educational Podcast', 'The traditional classroom model is undergoing a significant transformation in the digital age. Online learning platforms have made education more accessible to people around the world, breaking down geographical and financial barriers. However, this shift also presents challenges in maintaining student engagement and ensuring quality learning outcomes. Research suggests that blended learning approaches, combining online and in-person instruction, often yield the best results. The key is finding the right balance between technology and human interaction. Teachers must adapt their methods to engage students in virtual environments while maintaining the personal connection that fosters effective learning.', NULL, '{"duration": 180, "speed": "normal", "accent": "Canadian"}'),
('listening', 8, 'health', 'Health and Wellness Show', 'Mental health awareness has gained significant attention in recent years, particularly among young people. The stigma surrounding mental health issues is gradually decreasing, allowing more individuals to seek help and support. Research indicates that early intervention and treatment can significantly improve outcomes for people experiencing mental health challenges. Various approaches, including therapy, medication, and lifestyle changes, can be effective depending on individual circumstances. It''s important to recognize that mental health is just as crucial as physical health, and seeking professional help is a sign of strength, not weakness.', NULL, '{"duration": 210, "speed": "normal", "accent": "Canadian"}');

-- Insert sample questions for passages
INSERT INTO public.questions (passage_id, type, prompt, options, answer_key, meta) VALUES
((SELECT id FROM public.passages WHERE skill = 'reading' AND topic = 'environment' LIMIT 1), 'mcq', 'What is the main cause of climate change according to the passage?', '["Natural weather patterns", "Human activities, particularly burning fossil fuels", "Solar radiation", "Volcanic eruptions"]', '{"correct": 1, "explanation": "The passage clearly states that human activities, particularly the burning of fossil fuels, are driving climate change."}', '{"difficulty": "medium", "skill_focus": "main_idea"}'),
((SELECT id FROM public.passages WHERE skill = 'reading' AND topic = 'environment' LIMIT 1), 'mcq', 'What does the passage suggest about addressing climate change?', '["It requires only individual actions", "It requires only government policies", "It requires both individual actions and collective policy decisions", "It cannot be solved"]', '{"correct": 2, "explanation": "The passage states that addressing climate change requires both individual actions and collective policy decisions."}', '{"difficulty": "medium", "skill_focus": "inference"}'),
((SELECT id FROM public.passages WHERE skill = 'reading' AND topic = 'technology' LIMIT 1), 'mcq', 'What concern does the passage raise about AI?', '["It will make humans lazy", "It will replace all human workers", "It requires consideration of ethics, privacy, and future of work", "It will be too expensive"]', '{"correct": 2, "explanation": "The passage specifically mentions concerns about ethics, privacy, and the future of work regarding AI development."}', '{"difficulty": "hard", "skill_focus": "detail"}'),
((SELECT id FROM public.passages WHERE skill = 'listening' AND topic = 'education' LIMIT 1), 'mcq', 'What is the main advantage of online learning mentioned in the passage?', '["It is always cheaper", "It makes education more accessible", "It requires no teacher involvement", "It guarantees better results"]', '{"correct": 1, "explanation": "The passage states that online learning platforms have made education more accessible to people around the world."}', '{"difficulty": "easy", "skill_focus": "main_idea"}');

-- Insert sample badges
INSERT INTO public.badges (code, name, description, icon) VALUES
('first_practice', 'First Steps', 'Complete your first practice session', '🎯'),
('streak_7', 'Week Warrior', 'Maintain a 7-day study streak', '🔥'),
('band_improvement', 'Rising Star', 'Improve your band score by 2 points', '⭐'),
('skill_master', 'Skill Master', 'Achieve Band 9 in any skill', '🏆'),
('consistent_learner', 'Consistent Learner', 'Practice for 30 days in a row', '📚'),
('speed_demon', 'Speed Demon', 'Complete a reading passage in under 2 minutes', '⚡'),
('grammar_guru', 'Grammar Guru', 'Score 90%+ on grammar questions', '📝'),
('listening_expert', 'Listening Expert', 'Score 90%+ on listening questions', '👂');

-- Insert sample system prompts
INSERT INTO public.system_prompts (name, template, variables, version, active) VALUES
('speaking_evaluation', 'You are a CELPIP General Training speaking evaluator. Evaluate the following speaking response based on CELPIP criteria. Scoring Criteria (0-12 scale): - Content: Relevance and completeness of response to the prompt - Coherence: Logical organization and flow of ideas - Vocabulary: Range, precision, and appropriateness of word choice - Grammar: Accuracy of grammatical structures - Fluency: Speaking rate, pauses, and natural flow Return ONLY valid JSON with this exact structure: {"scores": {"content": 0-12, "coherence": 0-12, "vocabulary": 0-12, "grammar": 0-12, "fluency": 0-12}, "band": 1-12, "feedback": {"summary": "Brief overall assessment", "strengths": ["strength1", "strength2"], "improvements": ["improvement1", "improvement2"], "drills": ["drill1", "drill2"]}}', '["prompt", "transcript", "duration"]', 1, true),
('writing_evaluation', 'You are a CELPIP General Training writing evaluator. Evaluate the following writing response based on CELPIP criteria. Scoring Criteria (0-12 scale): - Task Fulfillment: How well the response addresses the prompt requirements - Organization: Logical structure, paragraphing, and coherence - Vocabulary: Range, precision, and appropriateness of word choice - Grammar: Accuracy of grammatical structures and sentence variety - Mechanics: Spelling, punctuation, and formatting Return ONLY valid JSON with this exact structure: {"scores": {"task_fulfillment": 0-12, "organization": 0-12, "vocabulary": 0-12, "grammar": 0-12, "mechanics": 0-12}, "band": 1-12, "feedback": {"summary": "Brief overall assessment", "strengths": ["strength1", "strength2"], "improvements": ["improvement1", "improvement2"], "suggestions": [{"start": 0, "end": 10, "replacement": "suggested text", "reason": "explanation"}]}}', '["task_type", "prompt", "text", "word_count"]', 1, true);

-- Insert sample study plan template
INSERT INTO public.study_plans (user_id, plan) VALUES
('00000000-0000-0000-0000-000000000000', '{"daily_goals": {"speaking": 2, "writing": 1, "reading": 2, "listening": 2}, "weekly_targets": {"vocabulary": 20, "grammar_focus": "complex_sentences", "practice_time": 300}, "focus_areas": ["improve_fluency", "expand_vocabulary", "grammar_accuracy"], "schedule": {"monday": ["speaking", "vocabulary"], "tuesday": ["writing", "reading"], "wednesday": ["listening", "grammar"], "thursday": ["speaking", "vocabulary"], "friday": ["writing", "reading"], "weekend": ["full_practice_test"]}}');
